stages:
    - build

variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: recursive

build:
    image: node:20
    stage: build
    script:
        - npm i
        - npm run build --workspaces
